name: Echo inputs from curl

on: 
  workflow_dispatch:
    branches:
      - main
    inputs:
      SHA:
        description: Sha to deploy
        required: false
        default: ""
      REPO_NAME:
        required: false
        default: ""
        description: Name of repo

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: echo "${{ github.event.inputs.SHA }} ${{ github.event.inputs.REPO_NAME }}"
      - name: ansible
        run: ansible-playbook --help
